name: linting-testing
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
      
jobs:
  checking:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm link
      - name: start linting
        run: npx eslint .
      - name: run tests
        run: npm test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
